from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.service import Service
from selenium.common.exceptions import NoSuchElementException

from config import USER_AGENT
from helper import (
    Helper,
    ElementChecker,
    DriverHelper
)
from helper import FileToSpreadsheetConverter


class ParserItemInfo(Helper):
    def __init__(self, source_file=''):
        self.options = webdriver.FirefoxOptions()
        self.options.set_preference(
            "general.useragent.override",
            USER_AGENT
        )
        self.options.set_preference("dom.webdriver.enabled", False)
        self.options.set_preference("intl.accept_languages", "en-us")
        self.options.set_preference("dom.webnotifications.enabled", False)

        self.service = Service(
            executable_path='GeckoDriver/geckodriver.exe'
        )

        self.driver = webdriver.Firefox(
            service=self.service,
            options=self.options
        )

        self.source_file = source_file
        self.folder = self.source_file.split('/')[0]

        self.checker = ElementChecker(driver=self.driver)
        self.driver_helper = DriverHelper(driver=self.driver)

        self.remove_duplicate(
            default=f"{self.folder}/cars_Unsorted_link.txt",
            sorted_filename=f"{self.folder}/cars_Sorted_link.txt",
        )

        self.iter_by_item()

    def iter_by_item(self):
        with open(self.source_file, mode='r') as file:
            source = file.read()

        for url in source.split():
            self.random_pause_code(start=1, stop=10)
            self.driver_helper.send_by_url(url=url)
            self.get_phone_number()

    def get_phone_number(self):
        """
        Extract phone numbers from the current item page.
        """

        self.random_pause_code(start=1, stop=20)

        root_container = self.driver.find_element(
            By.CLASS_NAME,
            'styles-module-scss-module__Q6jInW__container'
        )

        feature_element = root_container.find_element(
            By.CLASS_NAME,
            'styles-module-scss-module__RKm0hG__advert__info__container'
        )

        self.driver.execute_script(
            "arguments[0].scrollIntoView();",
            feature_element
        )

        self.random_pause_code(start=1, stop=16)

        button_class = (
            'styles-module-scss-module__BK5ZHa__button'
        )

        try:
            if  self.checker.class_exists(class_name='styles-module-scss-module__Q6jInW__container') and self.checker.class_exists(class_name=button_class):
                root_container = self.driver.find_element(
                    By.CLASS_NAME,
                    'styles-module-scss-module__ZAsrTa__phones'
                )

                root_container.find_element(
                    By.CLASS_NAME,
                    button_class
                ).click()

                self.random_pause_code(start=1, stop=16)

                container_phone = root_container.find_element(
                    By.CLASS_NAME,
                    'styles-module-scss-module__ZAsrTa__phones__wrapper'
                )

                for tag in container_phone.find_elements(By.TAG_NAME, 'a'):
                    phone = tag.get_attribute('href').replace('tel:', '')

                    self.crate_file(
                        filename=f"{self.folder}/{self.folder}_Unsorted_phone_number.txt",
                        mode='a',
                        data=phone
                    )

        except (NoSuchElementException,Exception):
            self.crate_file(
                filename=f"{self.folder}/{self.folder}_Not_phone_number.txt",
                mode='a',
                data=self.driver.current_url
            )

            return self.driver_helper.close_driver()

        return self.remove_duplicate(
            default=f"{self.folder}/{self.folder}_Unsorted_phone_number.txt",
            sorted_filename=f"{self.folder}/{self.folder}_Sorted_phone_number.txt",
        )


def main():
    return ParserItemInfo(
        source_file='cars/cars_Unsorted_link.txt'
    )


if __name__ == '__main__':
    main()

    # Initialize converter specifying destination directory for generated reports
    converter = FileToSpreadsheetConverter(output_dir="cars/reports")

    # Path to your sorted TXT numbers file generated by Helper pipeline
    source_txt_file = "cars/cars_Sorted_phone_number.txt"
    converter.convert_txt_to_excel(txt_file_path=source_txt_file,output_filename='cars_Sorted_phone_number')